import { Command } from 'commander';
import { readFileSync, writeFileSync, existsSync, renameSync } from 'node:fs';
import { createHash } from 'node:crypto';
import chalk from 'chalk';
import ora from 'ora';

import { getClient } from '../lib/api.js';
import { resolveContext } from '../lib/resolve.js';
import { requirePermission } from '../lib/permissions.js';
import * as output from '../lib/output.js';

function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    map.set(key, value);
  }
  return map;
}

function formatEnvFile(secrets: Map<string, string>): string {
  const lines: string[] = ['# Generated by CryptFlare CLI', `# ${new Date().toISOString()}`, ''];
  const sorted = [...secrets.entries()].sort(([a], [b]) => a.localeCompare(b));
  for (const [key, value] of sorted) {
    const needsQuotes = value.includes(' ') || value.includes('#') || value.includes('\n');
    lines.push(needsQuotes ? `${key}="${value}"` : `${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

export const pullCommand = new Command('pull')
  .description('Pull remote secrets to a local .env file')
  .option('-o, --org <id>', 'Organisation ID')
  .option('-w, --workspace <slug>', 'Workspace slug')
  .option('-e, --env <slug>', 'Environment slug')
  .option('-f, --file <path>', 'Output file path', '.env')
  .option('--overwrite', 'Overwrite existing file without confirmation')
  .option('--json', 'Output as JSON instead of .env format')
  .action(async (opts) => {
    try {
      const ctx = resolveContext(opts);
      const scope = { organisation: ctx.org, workspace: ctx.workspace, environment: ctx.env };
      const client = getClient();
      const spinner = ora('Fetching secrets...').start();

      const revealed = new Map<string, string>();
      let count = 0;
      const listPage = await client.secrets.list(scope);
      for await (const secret of listPage) {
        spinner.text = `Decrypting ${secret.key}...`;
        const data = await client.secrets.reveal({ ...scope, key: secret.key });
        revealed.set(data.key, data.value);
        count++;
      }

      if (count === 0) {
        spinner.info('No secrets found in this environment.');
        return;
      }

      spinner.stop();

      if (opts.json) {
        output.json(Object.fromEntries(revealed));
        return;
      }

      if (existsSync(opts.file) && !opts.overwrite) {
        output.warn(`File ${chalk.bold(opts.file)} already exists. Use ${chalk.bold('--overwrite')} to replace it.`);
        process.exit(1);
      }

      writeFileSync(opts.file, formatEnvFile(revealed), 'utf-8');
      output.success(`Pulled ${chalk.bold(String(revealed.size))} secrets to ${chalk.bold(opts.file)}`);
    } catch (err) {
      output.handleError(err);
    }
  });

export const pushCommand = new Command('push')
  .description('Push local .env file to remote environment')
  .option('-o, --org <id>', 'Organisation ID')
  .option('-w, --workspace <slug>', 'Workspace slug')
  .option('-e, --env <slug>', 'Environment slug')
  .option('-f, --file <path>', 'Input file path', '.env')
  .option('--dry-run', 'Show what would be pushed without making changes')
  .action(async (opts) => {
    try {
      const ctx = resolveContext(opts);
      const scope = { organisation: ctx.org, workspace: ctx.workspace, environment: ctx.env };
      const client = getClient();

      if (!existsSync(opts.file)) {
        output.warn(`File ${chalk.bold(opts.file)} not found.`);
        process.exit(1);
      }

      const content = readFileSync(opts.file, 'utf-8');
      const local = parseEnvFile(content);

      if (local.size === 0) {
        output.info('No secrets found in file.');
        return;
      }

      const spinner = ora('Comparing with remote...').start();

      const remoteKeys = new Set<string>();
      const remotePage = await client.secrets.list(scope);
      for await (const secret of remotePage) {
        remoteKeys.add(secret.key);
      }

      const toCreate: string[] = [];
      const toUpdate: string[] = [];
      for (const key of local.keys()) {
        if (remoteKeys.has(key)) toUpdate.push(key);
        else toCreate.push(key);
      }

      spinner.stop();

      if (opts.dryRun) {
        console.log();
        console.log(chalk.bold('  Dry run - no changes will be made'));
        console.log();
        if (toCreate.length > 0) {
          console.log(chalk.green(`  + ${toCreate.length} new secrets:`));
          toCreate.forEach((k) => console.log(chalk.green(`    + ${k}`)));
        }
        if (toUpdate.length > 0) {
          console.log(chalk.blue(`  ~ ${toUpdate.length} secrets to update:`));
          toUpdate.forEach((k) => console.log(chalk.blue(`    ~ ${k}`)));
        }
        console.log();
        return;
      }

      const pushSpinner = ora(`Pushing ${local.size} secrets...`).start();
      let pushed = 0;

      for (const [key, value] of local) {
        pushSpinner.text = `Pushing ${key}... (${pushed + 1}/${local.size})`;

        if (remoteKeys.has(key)) {
          await client.secrets.rotate({ ...scope, key, value });
        } else {
          await client.secrets.create({ ...scope, key, value });
        }
        pushed++;
      }

      pushSpinner.stop();
      output.success(`Pushed ${chalk.bold(String(pushed))} secrets (${chalk.green(`+${toCreate.length}`)} new, ${chalk.blue(`~${toUpdate.length}`)} updated)`);
    } catch (err) {
      output.handleError(err);
    }
  });

export const diffCommand = new Command('diff')
  .description('Compare local .env file with remote secrets')
  .option('-o, --org <id>', 'Organisation ID')
  .option('-w, --workspace <slug>', 'Workspace slug')
  .option('-e, --env <slug>', 'Environment slug')
  .option('-f, --file <path>', 'Input file path', '.env')
  .action(async (opts) => {
    try {
      const ctx = resolveContext(opts);
      const scope = { organisation: ctx.org, workspace: ctx.workspace, environment: ctx.env };
      const client = getClient();

      if (!existsSync(opts.file)) {
        output.warn(`File ${chalk.bold(opts.file)} not found.`);
        process.exit(1);
      }

      const content = readFileSync(opts.file, 'utf-8');
      const local = parseEnvFile(content);

      const spinner = ora('Comparing...').start();

      const remoteKeys = new Set<string>();
      const diffPage = await client.secrets.list(scope);
      for await (const secret of diffPage) {
        remoteKeys.add(secret.key);
      }

      spinner.stop();

      const onlyLocal: string[] = [];
      const onlyRemote: string[] = [];
      const common: string[] = [];

      for (const key of local.keys()) {
        if (remoteKeys.has(key)) common.push(key);
        else onlyLocal.push(key);
      }
      for (const key of remoteKeys) {
        if (!local.has(key)) onlyRemote.push(key);
      }

      if (onlyLocal.length === 0 && onlyRemote.length === 0) {
        output.success('Local and remote are in sync (keys match).');
        return;
      }

      console.log();
      if (onlyLocal.length > 0) {
        console.log(chalk.green(`  + ${onlyLocal.length} only in local (${opts.file}):`));
        onlyLocal.forEach((k) => console.log(chalk.green(`    + ${k}`)));
      }
      if (onlyRemote.length > 0) {
        console.log(chalk.red(`  - ${onlyRemote.length} only in remote:`));
        onlyRemote.forEach((k) => console.log(chalk.red(`    - ${k}`)));
      }
      if (common.length > 0) {
        console.log(chalk.dim(`  = ${common.length} in both (values not compared for security)`));
      }
      console.log();
    } catch (err) {
      output.handleError(err);
    }
  });

// ---------------------------------------------------------------------------
// `cf sync daemon` - long-running pull that watches a workspace + environment
// and rewrites a local .env file whenever the remote set of secrets changes.
//
// Why polling, not push: the API does not yet expose an SSE / webhook stream
// for arbitrary secret-set changes. Polling with bounded backoff keeps the
// pressure off the API and is honest about latency. Plan tracks an SSE
// upgrade as a follow-up; switching the loop body is the only change once
// the server endpoint ships.
// ---------------------------------------------------------------------------

const DAEMON_BASE_POLL_MS = 30_000;
const DAEMON_BACKOFF_CEILING_MS = 300_000;
const DAEMON_BACKOFF_MULTIPLIER = 2;
const DAEMON_NO_CHANGE_GRACE = 5; // polls before backoff kicks in
const DAEMON_JITTER_PCT = 0.1;

function jittered(ms: number, pct: number): number {
  const delta = ms * pct * (Math.random() * 2 - 1);
  return Math.max(1_000, Math.round(ms + delta));
}

function hashSecrets(secrets: Map<string, string>): string {
  const h = createHash('sha256');
  const keys = [...secrets.keys()].sort();
  for (const k of keys) h.update(`${k}=${secrets.get(k) ?? ''} `);
  return h.digest('hex');
}

async function pullSecretSet(
  client: ReturnType<typeof getClient>,
  scope: { organisation?: string; workspace: string; environment: string },
): Promise<Map<string, string>> {
  const set = new Map<string, string>();
  const list = await client.secrets.list(scope);
  for await (const secret of list) {
    const data = await client.secrets.reveal({ ...scope, key: secret.key });
    set.set(data.key, data.value);
  }
  return set;
}

function writeAtomic(path: string, body: string): void {
  const tmp = `${path}.tmp-${process.pid}`;
  writeFileSync(tmp, body, { encoding: 'utf-8', mode: 0o600 });
  renameSync(tmp, path);
}

export const daemonCommand = new Command('daemon')
  .description('Run a polling sync loop that rewrites a local .env file on remote changes')
  .option('-o, --org <id>', 'Organisation ID')
  .option('-w, --workspace <slug>', 'Workspace slug')
  .option('-e, --env <slug>', 'Environment slug')
  .option('-f, --file <path>', 'Output file path', '.env')
  .option('--interval <seconds>', 'Base poll interval in seconds (>=5)', String(DAEMON_BASE_POLL_MS / 1000))
  .option('--once', 'Run a single sync pass and exit (CI-friendly)')
  .option('-q, --quiet', 'Only log when the file changes')
  .action(async (opts) => {
    try {
      await requirePermission('secrets:read');
      const ctx = resolveContext(opts);
      const scope = { organisation: ctx.org, workspace: ctx.workspace, environment: ctx.env };
      const client = getClient();
      const baseIntervalMs = Math.max(5_000, Number(opts.interval) * 1_000);
      if (!Number.isFinite(baseIntervalMs)) {
        output.handleError(new Error(`Invalid --interval; expected a number, got ${opts.interval}`));
        return;
      }

      // Signal handling: SIGTERM / SIGINT flips a stop flag and the loop
      // exits cleanly on the next iteration boundary so we never leave a
      // half-written file or a phantom HTTPS connection open.
      let stop = false;
      const onSignal = (sig: NodeJS.Signals) => {
        if (stop) return;
        stop = true;
        console.error(chalk.dim(`\n[daemon] received ${sig}, stopping after current pass...`));
      };
      process.on('SIGTERM', onSignal);
      process.on('SIGINT', onSignal);

      console.error(chalk.bold(`[daemon] syncing ${ctx.workspace}/${ctx.env} -> ${opts.file} every ${baseIntervalMs / 1000}s`));

      let lastHash: string | null = null;
      let consecutiveNoChange = 0;
      let backoffMs = baseIntervalMs;

      while (!stop) {
        const startedAt = Date.now();
        try {
          const secrets = await pullSecretSet(client, scope);
          const nextHash = hashSecrets(secrets);

          if (nextHash !== lastHash) {
            const body = formatEnvFile(secrets);
            writeAtomic(opts.file, body);
            const action = lastHash === null ? 'wrote' : 'updated';
            console.error(chalk.green(`[daemon] ${action} ${opts.file} (${secrets.size} secrets)`));
            lastHash = nextHash;
            consecutiveNoChange = 0;
            backoffMs = baseIntervalMs;
          } else {
            consecutiveNoChange++;
            if (consecutiveNoChange >= DAEMON_NO_CHANGE_GRACE) {
              backoffMs = Math.min(backoffMs * DAEMON_BACKOFF_MULTIPLIER, DAEMON_BACKOFF_CEILING_MS);
            }
            if (!opts.quiet) {
              console.error(chalk.dim(`[daemon] no change (${secrets.size} secrets, next poll ${Math.round(backoffMs / 1000)}s)`));
            }
          }
        } catch (err) {
          // Reset backoff on transient API errors so we don't compound a
          // bad-network minute into a 5-minute lull. Keep going - the
          // daemon's job is to survive blips.
          consecutiveNoChange = 0;
          backoffMs = baseIntervalMs;
          console.error(chalk.red(`[daemon] pull failed: ${(err as Error).message ?? err}`));
        }

        if (opts.once || stop) break;

        const sleepMs = jittered(backoffMs, DAEMON_JITTER_PCT);
        await new Promise<void>((resolve) => {
          const t = setTimeout(resolve, sleepMs);
          // Wake immediately when a stop signal lands mid-sleep so SIGTERM
          // does not block for `backoffMs` before exiting.
          const onWake = () => { clearTimeout(t); resolve(); };
          process.once('SIGTERM', onWake);
          process.once('SIGINT', onWake);
        });
        void startedAt;
      }

      console.error(chalk.dim('[daemon] stopped'));
    } catch (err) {
      output.handleError(err);
    }
  });
